# Generated by Django 3.1.4 on 2020-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reifeicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('tipo_de_refeiçao', models.IntegerField()),
                ('alunos', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='RequestIF',
        ),
    ]
