# Generated by Django 3.1.4 on 2020-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reifeicao', '0003_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_de_refeiçao',
            field=models.IntegerField(choices=[(0, 'Jantar'), (1, 'Almoço')]),
        ),
    ]
